/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as SettingsImport } from "./routes/settings";
import { Route as BookIdImport } from "./routes/book.$id";
import { Route as ReadIdFormatImport } from "./routes/read-route";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const SettingsRoute = SettingsImport.update({
  path: "/settings",
  getParentRoute: () => rootRoute,
} as any);

const BookIdRoute = BookIdImport.update({
  path: "/book/$id",
  getParentRoute: () => rootRoute,
} as any);

const ReadIdFormatRoute = ReadIdFormatImport.update({
  path: "/read/$id/$format",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsImport;
      parentRoute: typeof rootRoute;
    };
    "/book/$id": {
      id: "/book/$id";
      path: "/book/$id";
      fullPath: "/book/$id";
      preLoaderRoute: typeof BookIdImport;
      parentRoute: typeof rootRoute;
    };
    "/read/$id/$format": {
      id: "/read/$id/$format";
      path: "/read/$id/$format";
      fullPath: "/read/$id/$format";
      preLoaderRoute: typeof ReadIdFormatImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SettingsRoute,
  BookIdRoute,
  ReadIdFormatRoute,
]);

/* prettier-ignore-end */
